fixtures:
  repositories:
    archive:
      repo: "git@github.com:puppet-community/puppet-archive.git"
    pe_gem:
      repo: "git@github.com:puppetlabs/puppetlabs-pe_gem.git"
    stdlib:
      repo: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
  symlinks:
      packer: "#{source_dir}"
