fixtures:
  repositories:
    archive:
      repo: "https://github.com/puppet-community/puppet-archive.git"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
      'packer': '#{source_dir}'
